### ISSUE TITLE
Does the scfb driver not have double buffering to prevent screen tearing?

### ISSUE THREAD

**Issue by Food-of-India** [rayddteam/xf86-video-scfb#5]
I have screen tearing when using the scfb driver. It's the only Xorg display driver that I can use with my laptop computer. Double buffering is a programming technique to prevent screen tearing.

**Comment by rayddteam** [comment]
Hi Sean!
scfb driver does not create frame buffer, it just use given one.
For example, most modern UEFI enabled systems has FB created by UEFI BIOS. So, there is no way to configure double buffering.
